# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

social_sharing: true
github_username:  jekyll
google_analytic_id:
disqus_name:

permalink: /:categories/:title
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num.html'
  title: ':title - page :num'
  sort_reverse: true

autopages:
  enabled: true
  categories:
    title: 'Posts in category :cat'
  tags:
    title: 'Posts tagged with :tag'
  collections:
    title: 'Posts in collection :coll'

# jekyll seo tag settings
logo: assets/images/example-image.png
twitter:
  username: jekyllrb

# Build settings
markdown: kramdown
sass:
  style: compressed